# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@domain.com
author: GitHub User
copyright: Copyright Â© 1970-2010
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "" # the favicon for your site

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%b %-d, %Y"

# If you want more debug log, you can set true
# debug: false

# If you want transparent header, you can set true
# header_transparent: false

# Google analytics
# google_analytics: [Tracking ID]

# If you want to generate website sitemap, you can set true
# sitemap: false

# If you want to change site language, you can set lang option
# lang: "en"  # default lang is en

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
# translate_langs:
#   - lang: en
#     text: English
#
#   - lang: fr
#     img: https://www.countryflags.io/fr/flat/64.png
#     text: Franch
#
#   - lang: zh-CN
#     img: https://www.countryflags.io/cn/flat/64.png
#     text: Chinese(Simple)
#
#   - lang: zh-TW
#     img: https://www.countryflags.io/tw/flat/64.png
#     text: Chinese(Traditional)
#
#   - lang: ja
#     img: https://www.countryflags.io/jp/flat/64.png
#     text: Japan
#
#   - lang: ko
#     img: https://www.countryflags.io/kr/flat/64.png
#     text: Korean
#
#   - lang: ru
#     img: https://www.countryflags.io/ru/flat/64.png
#     text: Russia

# You can choose a theme color
# Default theme colors as below:
# spacegrey: #353535
# inkpurple: #543581
# aquablue: #00aaa0
# azureblue: #2863b1
# gracered: #a12a50
# aloegreen: #3d9e56
# rustbrown: #795548
#
# theme_color: spacegrey
#
# Custom color as below:
# theme_color: "#882250"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - index.html
#   - archives.html
#   - categories.html
#   - tags.html

# Page default value
# defaults:
#   home:
#     heading: "Your awesome heading"
#     subheading: "Your awesome subheading"
#     banner: "Your image url"

# Pagination setting
# paginate: 5

# Disqus comments
# disqus:
#   shortname: "Your Disqus username"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
